<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>m</string>
		<string>nb</string>
	</array>
	<key>foldingStartMarker</key>
	<string></string>
	<key>foldingStopMarker</key>
	<string></string>
	<key>name</key>
	<string>Mathematica</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>\(\*</string>
			<key>end</key>
			<string>\*\)</string>
			<key>name</key>
			<string>comment.block.mathematica</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.mathematica</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.untitled</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>\b[a-zA-Z$][\w$]*((?=_{1,3})|(?=\s*:(?![=:&gt;])))</string>
			<key>name</key>
			<string>variable.parameter.mathematica</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(True|False|Null|Automatic|All)\b</string>
			<key>name</key>
			<string>keyword.language.mathematica</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(Pi|I|E)\b</string>
			<key>name</key>
			<string>keyword.math.mathematica</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\+|-(?!&gt;)|/(?![;/@.])|\*|\^</string>
			<key>name</key>
			<string>keyword.operator.arithmetic.mathematica</string>
		</dict>
		<dict>
			<key>match</key>
			<string>/;|&amp;&amp;|\|\|</string>
			<key>name</key>
			<string>keyword.operator.logical.mathematica</string>
		</dict>
		<dict>
			<key>match</key>
			<string>/{1,2}@|@{1,3}</string>
			<key>name</key>
			<string>keyword.operator.functional.mathematica</string>
		</dict>
		<dict>
			<key>match</key>
			<string>-&gt;|:&gt;|/.</string>
			<key>name</key>
			<string>keyword.operator.rules.mathematica</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(\d+)</string>
			<key>name</key>
			<string>constant.numeric.integer.mathematica</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(\d+\.\d*)</string>
			<key>name</key>
			<string>constant.numeric.float.mathematica</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b([a-zA-Z$][\w$]*)\[</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.mathematica</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\]</string>
			<key>name</key>
			<string>meta.full_form.mathematica</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>brackets</key>
		<dict>
			<key>begin</key>
			<string>\[</string>
			<key>end</key>
			<string>\]</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#brackets</string>
				</dict>
			</array>
		</dict>
		<key>generic_symbol</key>
		<dict>
			<key>match</key>
			<string>[a-zA-Z$][\w$]*</string>
		</dict>
		<key>list</key>
		<dict>
			<key>begin</key>
			<string>\{</string>
			<key>end</key>
			<string>\}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#list</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.mathematica</string>
	<key>uuid</key>
	<string>EB28CBAC-55D2-4CAD-B996-2F4A44FDF2B8</string>
</dict>
</plist>
