<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>m</string>
		<string>nb</string>
	</array>
	<key>foldingStartMarker</key>
	<string>\[\s*$</string>
	<key>foldingStopMarker</key>
	<string>^\s*\]</string>
	<key>keyEquivalent</key>
	<string>^~M</string>
	<key>name</key>
	<string>Mathematica</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#array_index</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#constant</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#sqlstring</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#string</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#number</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#list</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#emptyfunction</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#function</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#symbol</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#named_pattern</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\^:=</string>
			<key>name</key>
			<string>keyword.operator.assignment.up_set_delayed</string>
		</dict>
		<dict>
			<key>match</key>
			<string>===</string>
			<key>name</key>
			<string>keyword.operator.logical.equivalent</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\&gt;\&gt;\&gt;</string>
			<key>name</key>
			<string>keyword.operator.mathematica.put_append</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\*\^</string>
			<key>name</key>
			<string>keyword.operator.arithmetic.scientific_notation</string>
		</dict>
		<dict>
			<key>match</key>
			<string>:=</string>
			<key>name</key>
			<string>keyword.operator.assignment.set_delayed</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\^=</string>
			<key>name</key>
			<string>keyword.operator.assignment.up_set</string>
		</dict>
		<dict>
			<key>match</key>
			<string>&amp;&amp;</string>
			<key>name</key>
			<string>keyword.operator.logical.and</string>
		</dict>
		<dict>
			<key>match</key>
			<string>||</string>
			<key>name</key>
			<string>keyword.operator.logical.or</string>
		</dict>
		<dict>
			<key>match</key>
			<string>==</string>
			<key>name</key>
			<string>keyword.operator.logical.equal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\&gt;=</string>
			<key>name</key>
			<string>keyword.operator.logical.greater_than_or_equal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\&lt;=</string>
			<key>name</key>
			<string>keyword.operator.logical.less_than_or_equal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>;;</string>
			<key>name</key>
			<string>keyword.operator.mathematica.span</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\.\.</string>
			<key>name</key>
			<string>keyword.operator.mathematica.repeated</string>
		</dict>
		<dict>
			<key>match</key>
			<string>/\.</string>
			<key>name</key>
			<string>keyword.operator.mathematica.replace</string>
		</dict>
		<dict>
			<key>match</key>
			<string>-\&gt;</string>
			<key>name</key>
			<string>keyword.operator.mathematica.rule</string>
		</dict>
		<dict>
			<key>match</key>
			<string>:\&gt;</string>
			<key>name</key>
			<string>keyword.operator.mathematica.rule_delayed</string>
		</dict>
		<dict>
			<key>match</key>
			<string>@{1,3}</string>
			<key>name</key>
			<string>keyword.operator.mathematica.apply</string>
		</dict>
		<dict>
			<key>match</key>
			<string>/@</string>
			<key>name</key>
			<string>keyword.operator.mathematica.map</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\&lt;\&gt;</string>
			<key>name</key>
			<string>keyword.operator.mathematica.string_join</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\&lt;\&lt;</string>
			<key>name</key>
			<string>keyword.operator.mathematica.get</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\&gt;\&gt;</string>
			<key>name</key>
			<string>keyword.operator.mathematica.put</string>
		</dict>
		<dict>
			<key>match</key>
			<string>/;</string>
			<key>name</key>
			<string>keyword.operator.mathematica.condition</string>
		</dict>
		<dict>
			<key>match</key>
			<string>//</string>
			<key>name</key>
			<string>keyword.operator.mathematica.postfix</string>
		</dict>
		<dict>
			<key>match</key>
			<string>~~</string>
			<key>name</key>
			<string>keyword.operator.mathematica.string_expression</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\+</string>
			<key>name</key>
			<string>keyword.operator.arithmetic.plus</string>
		</dict>
		<dict>
			<key>match</key>
			<string>-</string>
			<key>name</key>
			<string>keyword.operator.arithmetic.minus</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\*</string>
			<key>name</key>
			<string>keyword.operator.arithmetic.times</string>
		</dict>
		<dict>
			<key>match</key>
			<string>/</string>
			<key>name</key>
			<string>keyword.operator.arithmetic.divide</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\^</string>
			<key>name</key>
			<string>keyword.operator.arithmetic.power</string>
		</dict>
		<dict>
			<key>match</key>
			<string>!</string>
			<key>name</key>
			<string>keyword.operator.logical.not</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\&gt;</string>
			<key>name</key>
			<string>keyword.operator.logical.greater_than</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\&lt;</string>
			<key>name</key>
			<string>keyword.operator.logical.less_than</string>
		</dict>
		<dict>
			<key>match</key>
			<string>|</string>
			<key>name</key>
			<string>keyword.operator.mathematica.alternative</string>
		</dict>
		<dict>
			<key>match</key>
			<string>@</string>
			<key>name</key>
			<string>keyword.operator.mathematica.prefix</string>
		</dict>
		<dict>
			<key>match</key>
			<string>;</string>
			<key>name</key>
			<string>keyword.operator.mathematica.compound_expression</string>
		</dict>
		<dict>
			<key>match</key>
			<string>`</string>
			<key>name</key>
			<string>keyword.operator.mathematica.context</string>
		</dict>
		<dict>
			<key>match</key>
			<string>&amp;</string>
			<key>name</key>
			<string>keyword.operator.mathematica.function</string>
		</dict>
		<dict>
			<key>match</key>
			<string>#\d*</string>
			<key>name</key>
			<string>keyword.operator.mathematica.slot</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\?</string>
			<key>name</key>
			<string>keyword.operator.mathematica.pattern_test</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>array_index</key>
		<dict>
			<key>begin</key>
			<string>\[\[</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.part.begin.mathematica</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\]\]</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.part.end.mathematica</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.structure.part.mathematica</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>match</key>
					<string>,</string>
					<key>name</key>
					<string>punctuation.separator.part.mathematica</string>
				</dict>
			</array>
		</dict>
		<key>comment</key>
		<dict>
			<key>begin</key>
			<string>\(\*</string>
			<key>end</key>
			<string>\*\)</string>
			<key>name</key>
			<string>comment.block.mathematica</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
			</array>
		</dict>
		<key>constant</key>
		<dict>
			<key>match</key>
			<string>\b(True|False|Null|Automatic|All|None|Infinity)\b</string>
			<key>name</key>
			<string>constant.language.mathematica</string>
		</dict>
		<key>emptyfunction</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.empty.mathematica</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.function.empty.begin.mathematica</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>meta.scope.between_empty_brackets</string>
				</dict>
			</dict>
			<key>match</key>
			<string>([a-zA-Z$][a-zA-Z0-9$]*)(\[)(\])</string>
			<key>name</key>
			<string>meta.structure.function.empty.mathematica</string>
		</dict>
		<key>function</key>
		<dict>
			<key>begin</key>
			<string>([a-zA-Z$][a-zA-Z0-9$]*)(\[)(?!\[)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.mathematica</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.function.begin.mathematica</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\]</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.function.end.mathematica</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.structure.function.mathematica</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>include</key>
					<string>meta.scope.any.mathematica</string>
				</dict>
				<dict>
					<key>match</key>
					<string>,</string>
					<key>name</key>
					<string>punctuation.separator.list.mathematica</string>
				</dict>
			</array>
		</dict>
		<key>list</key>
		<dict>
			<key>begin</key>
			<string>\{</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.list.begin.mathematica</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.list.end.mathematica</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.structure.list.mathematica</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>match</key>
					<string>,</string>
					<key>name</key>
					<string>punctuation.separator.list.mathematica</string>
				</dict>
			</array>
		</dict>
		<key>named_pattern</key>
		<dict>
			<key>match</key>
			<string>[a-zA-Z$][a-zA-Z0-9$]*_([a-zA-Z$])*\b</string>
			<key>name</key>
			<string>variable.named_pattern.mathematica</string>
		</dict>
		<key>number</key>
		<dict>
			<key>match</key>
			<string>\b(\d+(\.\d*)?)</string>
			<key>name</key>
			<string>constant.numeric.mathematica</string>
		</dict>
		<key>sqlstring</key>
		<dict>
			<key>begin</key>
			<string>"(?=\s*(SELECT|INSERT|UPDATE|DELETE|CREATE|REPLACE|ALTER))</string>
			<key>comment</key>
			<string>double quoted string</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.sql.mathematica</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#constant_placeholder</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#escaped_char</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.sql</string>
				</dict>
			</array>
		</dict>
		<key>string</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.mathematica</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.untitled</string>
				</dict>
			</array>
		</dict>
		<key>symbol</key>
		<dict>
			<key>match</key>
			<string>[a-zA-Z$][a-zA-Z0-9$]*\b</string>
			<key>name</key>
			<string>variable.symbol.mathematica</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.mathematica</string>
	<key>uuid</key>
	<string>EB28CBAC-55D2-4CAD-B996-2F4A44FDF2B8</string>
</dict>
</plist>
